### ISSUE TITLE
Logging trace events to file format CLEF

### ISSUE THREAD

**Issue by TomDC-DX** [serilog-tracing/serilog-tracing#161] opened 2024-12-02 14:48 UTC
Hello,

We are using the [CLEF ](https://github.com/serilog/serilog-formatting-compact) file format exporter for logging all application events as a backup method, next to sending them to [SEQ ](https://datalust.co/seq).

When importing those files into SEQ, we do not find any tracings anymore.
I'm wondering now if the compact logging format is the reason for this?

Any idea if I have to modify the format to also include all the data that is being generated by SerilogTracing?

Below an example of the CLEF format when an event is logged:

`{"@t":"2024-11-29T10:04:01.8757430Z","@mt":"HTTP {RequestMethod} {RequestUri}","@tr":"18f3ab38dc32dcec64a2b3488b129578","@sp":"7752d49f81144272","RequestMethod":"GET","RequestUri":"http://localhost:7023/api/v1/activity","StatusCode":200,"http.request.method":"GET","server.address":"localhost","server.port":7023,"url.full":"http://localhost:7023/api/v1/activity?page=Redacted&pageSize=Redacted","network.protocol.version":"1.1","http.response.status_code":200,"SpanStartTimestamp":"2024-11-29T10:04:01.8413844Z","ParentSpanId":"bd1ff0225e7b3915","SpanKind":"Client","SourceContext":"OpenTelemetry.Instrumentation.Http.HttpClient","CorrelationId":"18f3ab38dc32dcec64a2b3488b129578","UserId":"anonymous","HttpMethod":"GET","Uri":"http://localhost:7023/api/v1/activity?page=0&pageSize=100","ActionId":"83ad7732-5d19-45e6-b970-fce724327295","ActionName":"Project.Api.Controllers.v1.Demo.DemoController.GetActivitiesFromFlow (Project.Api)","RequestId":"0HN8FI3P5EFI0:00000005","RequestPath":"/api/v1/demos/RemoteApiCall/Flow/Activities","ConnectionId":"0HN8FI3P5EFI0","Scope":["HTTP GET http://localhost:7023/api/v1/activity?page=0&pageSize=100"],"MachineName":"DXTDC","EnvironmentName":"Development","ThreadId":155,"Application":"Project.Api"}`

Thanks!

**Comment by KodrAus** [comment] 2024-12-02 20:42
Hi @TomDC-DX! :wave:

The issue here is the names chosen for some span properties by SerilogTracing don't match what Seq expects them to be:

- `SpanStartTimestamp` needs to be `@st`.
- `ParentSpanId` needs to be `@ps`.

The full set of well-known properties in Seq [can be found here](https://docs.datalust.co/docs/posting-raw-events#reified-properties).

This isn't an issue with SerilogTracing, because those properties are extensions to the data model, it isn't really up to SerilogTracing to make them compatible with Seq, but does demonstrate a bit of a gap.

I think you should be able to use [`Serilog.Expressions`](https://github.com/serilog/serilog-expressions) to render events into CLEF using the property names Seq expects. Let us know if you need a hand with producing an expression that renders your events as CLEF.

If performance is a concern, you can also [pull and adapt the compact formatter source](https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/CompactJsonFormatter.cs), which is written to be hackable.

**Comment by nblumhardt** [comment] 2024-12-02 22:13
This one is a duplicate of https://github.com/datalust/seq-tickets/discussions/2329, where there is some more information, I've answered over there.

**Comment by KodrAus** [comment] 2024-12-02 23:44
Closing in favour of https://github.com/datalust/seq-tickets/discussions/2329

**Closed by KodrAus** 2024-12-02 23:44 UTC

**Comment by TomDC-DX** [comment] 2024-12-04 09:21
Just wanted to add a conclusion to my ticket.

For possible people who arrive here in their search => use **seqcli ingest -i <filename.clef>** to import clef generated files
